version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  optiplex:
    build: .
    container_name: optiplex
    restart: always
    expose:
      - 8080
    environment:
      - REDIS_HOST=redis_db
      - SECRET_KEY=dev
    networks:
      - internal
    # store db and other stuff outside the container (skip init-db in Dockerfile)
    volumes:
      - ./instance:/instance

  nginx:
    image: nginx:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.optiplex.rule=Host(`optiplex.revwal.de`)"
      - "traefik.http.routers.optiplex.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      - "traefik.http.routers.optiplex.tls.certresolver=myresolver"
    networks:
      - web
      - internal
    ports:
      - 5000:80
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./optiplex/static:/static:ro

  redis_db:
    image: redis:latest
    restart: always
    networks:
     - internal
