version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
 optiplex:
    image: optiplex:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.optiplex.rule=Host(`optiplex.revwal.de`)"
      - "traefik.http.routers.optiplex.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      - "traefik.http.routers.optiplex.tls.certresolver=myresolver"
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis_db
      - SECRET_KEY=dev
    networks:
      - web
      - internal

 redis_db:
    image: redis:latest
    restart: always
    networks:
     - internal